---
categories:
  added: Added
  changed: Changed
  deprecated: Deprecated
  removed: Removed
  fixed: Fixed
template: |
  {% if categories %}
  {% each categories %}
  ### {{ title }}

  {% each entries %}
  - [{{ title }}]({{ commit.reference }}) by {{ author.reference }} {% if merge_request %} ([merge request]({{ merge_request.reference }})){% end %}

  {% end %}

  {% end %}
  {% else %}
  No changes.
  {% end %}
